# This is a basic workflow to help you get started with Actions

name: Ansible Lint

# Controls when the workflow will run
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  
  - name: Run ansible-lint
  # uses: ansible-community/ansible-lint-action@ba54de22a6edeea3aa385cd8c5f20ec1f960a30b
    uses: ansible-community/ansible-lint-action@v6
    with: 
    # Arguments to be passed to the ansible-lint.

    args: # optional, default is .
